trigger:
    - deploy

# Do not run on PR builds
pr: none

jobs:
    - job: Deploy
      displayName: "Build and Publish"
      pool:
          vmImage: "Ubuntu-latest"
          demands: npm
      steps:
          - script: "npm install"
            displayName: "Npm install and build"
          - script: "npm run test"
            displayName: "Jest Unit Tests"
          - script: "npm run preparePublish"
            displayName: "Npm preparePublish (version setting, cross-package dependency configuration)"
          - task: Npm@1
            displayName: "Npm publish"
            inputs:
                command: "custom"
                customCommand: "publish --tag preview --access public -w @babylonjs/smart-filters && publish --tag preview --access public -w @babylonjs/smart-filters-editor"
                customEndpoint: "NPMWithAccessToken"
